services:
  # Development service
  bot-dev:
    container_name: gianteevee-backend-dev
    image: gianteevee-backend-dev
    build:
      context: .
      target: dev
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      
  # Production service
  bot-prod:
    container_name: gianteevee-backend-prod
    image: gianteevee-backend-prod
    build:
      context: .
      target: prod
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
