version: '3.4'

services:
  gianteeveetwurple:
    image: gianteeveetwurple
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
